# Generated by Django 4.1.5 on 2023-01-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArticaleApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporter",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
