# Generated by Django 4.1.5 on 2023-01-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArticaleApp", "0002_alter_reporter_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporter",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
