# Generated by Django 4.1.5 on 2023-01-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ArticaleApp", "0003_alter_reporter_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="reporter",
            new_name="reporter_Id",
        ),
    ]
