# Generated by Django 4.1.5 on 2023-02-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArticaleApp", "0005_rename_reporter_id_article_reporter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporter",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
