# Generated by Django 4.1.5 on 2023-02-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArticaleApp", "0006_alter_reporter_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="pub_date",
        ),
        migrations.AddField(
            model_name="article",
            name="time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
